const contentTypes = {
    "html" : "text/html;charset=UTF-8",
    "css" : "text/css;charset=UTF-8",
    "js" : "text/javascript;charset=UTF-8",
    "jpg" : "image/jpeg",
    "jpeg" : "image/jpeg",
    "gif" : "image/gif",
    "png" : "image/png",
    "svg" : "image/svg+xml",
    "webp" : "image/webp",
    "ico" : "image/x-icon",
    "collection":"font/collection",
    "otf" :"font/otf",
    "sfnt"	:"font/sfnt",
    "ttf":	"font/ttf",
    "woff":"font/woff",
    "woff2":"font/woff2",
    "json" : "application/json;charset=UTF-8",
    "mp3" : "audio/mpeg",
    "ogg" : "video/ogg",
    "mp4" : "video/mp4",
    "avi" : "video/avi",
    "webm" : "video/webm"
};